// Add these to the BRAND_MAP in import_from_csv.js

// === FIXES FOR EXISTING MAPPINGS ===
// Replace these incorrect mappings:
// 'm.k.l': 'Michael Kors' → 'm.k.l': 'Moncler'
// 'm.l.b': 'NYC' → 'm.l.b': 'MLB'  
// 'p.l.d': 'Prada' → 'p.l.d': 'Polo Ralph Lauren'
// 'a.m.e': 'Amiri' → 'a.m.e': 'AMI'
// 'a.m.n': 'Amina Muaddi' → 'a.m.n': 'Amiri'
// 'a.m.s': 'AMS' → 'a.m.s': 'Alexander McQueen'
// 'b.r.o': 'BRO' → 'b.r.o': 'Broken Planet'
// 'k.h.t': 'Carhartt' → 'k.h.t': 'Kith'

// === NEW MAPPINGS TO ADD ===
const additionalMappings = {
  // Full dotted brand names
  'm.a.s.c.o.t': 'Mascot',
  's.k.a.t.e.b.o.a.r.d': 'Skateboard',
  's.k.a.t.e.s': 'Skates',
  'p.a.n.t.a.l.o.n': 'Pants',
  'N.i.k.e': 'Nike',
  'N.I.K.E': 'Nike',
  'M.a.r.g.i.e.l.a': 'Maison Margiela',
  'D.i.o.r': 'Dior',
  'D.i.o': 'Dior',
  'M.o.n.c.l.e.r': 'Moncler',
  'M.o.n': 'Moncler',
  'S.t.u.s.s.y': 'Stussy',
  'S.t.u': 'Stussy',
  'm.i.u.m.i.u': 'Miu Miu',
  'u.g.g': 'UGG',
  'C.o.r.t.e.i.z': 'Corteiz',
  'C.o.r': 'Corteiz',
  'l.a.c.o.s.t.e': 'Lacoste',
  'V.E.J.A': 'Veja',
  'E.S.S': 'Essentials',
  'A.n.g.e.l': 'Palm Angels',
  'A.n.g': 'Palm Angels',
  't.o.r.o.m': 'Torom',
  'T.O.R.O.M': 'Torom',
  'E.m.p.e.r.o.r': 'Emperor',
  'E.m.p': 'Emperor',
  'R.a.c.i.n.g': 'Racing',
  'R.a.c': 'Racing',
  'H.e.l.l S.t.a.r': 'Hellstar',
  'H.e.l': 'Hellstar',
  'S.t.a.r': 'Star',
  'S.t.a': 'Star',
  'g.i.u.s.e.p.p.e z.a.n.o.t.t.i': 'Giuseppe Zanotti',
  'g.i.u.s.e.p.p.e': 'Giuseppe',
  'z.a.n.o.t.t.i': 'Zanotti',
  'B.o.t.t.e.g.a V.e.n.e.t.a': 'Bottega Veneta',
  'B.o.t.t.e.g.a': 'Bottega Veneta',
  'B.o.t': 'Bottega Veneta',
  'V.e.n.e.t.a': 'Veneta',
  'V.e.n': 'Veneta',
  'A.m.e.r.i.c.a.n': 'American',
  'A.m.e': 'American',
  'K.a.p.o.k': 'Kapok',
  'K.a.p': 'Kapok',
  'N.a.i.l': 'Nail',
  'N.a.i': 'Nail',
  'f.l.e': 'Fleece',
  'F.L.E': 'Fleece',
  'c.a.r.g.o': 'Cargo',
  'C.A.R.G.O': 'Cargo',
  'C.h.r.o.m.e H.e.a.r.t.s': 'Chrome Hearts',
  'C.h.r.o.m.e': 'Chrome',
  'C.h.r': 'Chrome',
  'H.e.a.r.t.s': 'Hearts',
  'H.e.a': 'Hearts',
  'G.i.v.e.n.c.h.y': 'Givenchy',
  'G.i.v': 'Givenchy',
  'P.a.t.e.k Philippe': 'Patek Philippe',
  'P.a.t': 'Patek',
  'A.u.d.e.m.a.r.s P.i.g.u.e.t': 'Audemars Piguet',
  'A.u.d': 'Audemars',
  'P.i.g.u.e.t': 'Piguet',
  'P.i.g': 'Piguet',
  'N.o.r.t.h Face': 'The North Face',
  'N.o.r.t.h': 'North',
  'N.o.r': 'North',
  'e.s.s.e.n.t.i.a.l.s': 'Essentials',
  'R.a.l.p.h Lauren': 'Ralph Lauren',
  'R.a.l.p.h': 'Ralph Lauren',
  'R.a.l': 'Ralph',
  'C.h.a.n.e.l': 'Chanel',
  'C.h.a': 'Chanel',
  'F.e.n.d.i': 'Fendi',
  'F.e.n': 'Fendi',
  'V.e.r.s.a.c.e': 'Versace',
  'V.e.r': 'Versace',
  'G.o.t.h.i.c': 'Gothic',
  'G.o.t': 'Gothic',
  'G.o.y.a.d': 'Goyard',
  'G.o.y': 'Goyard',
  'C.a.r.t.i.e.r': 'Cartier',
  'J.o.r.d.a.n': 'Jordan',
  'J.o.r': 'Jordan',
  'M.c.Q.u.e.e.n': 'McQueen',
  'M.c.Q.u.e': 'McQueen',
  'U.n.i.q.l.o': 'Uniqlo',
  'U.n.i': 'Uniqlo',
  'S.a.i.n.t Laurent': 'Saint Laurent',
  'S.a.i.n.t': 'Saint Laurent',
  'S.a.i': 'Saint',
  'R.a.y-B.a.n': 'Ray-Ban',
  'R.a.y': 'Ray',
  'B.a.n': 'Ban',
  'C.a.n.a.d.a Goose': 'Canada Goose',
  'C.a.n.a.d.a': 'Canada Goose',
  'C.a.n': 'Canada',
  'S.a.n.y.u.a.n': 'Sanyuan',
  'S.a.n': 'Sanyuan',
  'C.A.R.R.ERA': 'Carrera',
  'C.A.R.R': 'Carrera',
  
  // 2-letter codes
  'a.r': 'AR',
  'A.R': 'AR',
  't.u': 'TU',
  'T.U': 'TU',
  'n.a': 'NA',
  'N.A': 'NA',
  'h.e': 'HE',
  'H.E': 'HE',
  'v.i': 'VI',
  'V.I': 'VI',
  'K.N': 'KN',
  'g.z': 'GZ',
  'G.Z': 'GZ',
  'f.r': 'FR',
  'F.R': 'FR',
  'l.w.s': 'LWS',
  'L.W.S': 'LWS',
  'v.a': 'VA',
  'V.A': 'VA',
  'j.n.d': 'JND',
  'J.N.D': 'JND',
  'b.l.s.j': 'BLSJ',
  'T.K': 'TK',
  'g.e.r': 'GER',
  'G.E.R': 'GER',
  'c.a.s.a': 'Casa',
  'd.n': 'DN',
  'D.N': 'DN',
  'R.C': 'RC',
  'd.y': 'DY',
  'D.Y': 'DY',
  's.k.n': 'SKN',
  'S.K.N': 'SKN',
  'A.I.R': 'AIR',
  'v.i.n.t.a.g': 'Vintage',
  'a.f': 'AF',
  'A.F': 'AF',
  'G.U': 'GU',
  'D.C': 'DC',
  's.u.t': 'SUT',
  'S.U.T': 'SUT',
  'z.y': 'ZY',
  'Z.Y': 'ZY',
  'b.o.n.e': 'Bone',
  't.e': 'TE',
  'T.E': 'TE',
  'c.a': 'CA',
  'C.A': 'CA',
  'c.o': 'CO',
  'C.O': 'CO',
  
  // Additional Nike/Jordan/Yeezy variations
  'y.z 450': 'Yeezy 450',
  'y.z 700': 'Yeezy 700',
  'y.z 380': 'Yeezy 380',
  'a.j.6': 'Air Jordan 6',
  'A.J.6': 'Air Jordan 6',
};

module.exports = additionalMappings;
